package newcast

import (
	"bytes"
	"errors"
	"fmt"
	"image"
	"image/png"
	"io"
	"math"
)

const ScaleFactor = 100.0

type Frame struct {
	Width  int
	Height int
	Data   []Vector
}

func NewFrame(width, height int) *Frame {
	return &Frame{
		Width:  width,
		Height: height,
		Data:   make([]Vector, width*height),
	}
}

func (f *Frame) Set(x, y int, v Vector) {
	if x >= 0 && x < f.Width && y >= 0 && y < f.Height {
		f.Data[y*f.Width+x] = v
	}
}

func (f *Frame) Get(x, y int) Vector {
	if x >= 0 && x < f.Width && y >= 0 && y < f.Height {
		return f.Data[y*f.Width+x]
	}
	return Vector{}
}

// MarshalPNG converts the Frame into a standard 8-bit RGBA PNG.
// It packs 16-bit values across 2 channels.
// X -> Red (High), Green (Low)
// Y -> Blue (High), Alpha (Low)
func (f *Frame) MarshalPNG() ([]byte, error) {
	rect := image.Rect(0, 0, f.Width, f.Height)
	// Use NRGBA to avoid alpha pre-multiplication corruption
	img := image.NewNRGBA(rect)

	i := 0
	for y := 0; y < f.Height; y++ {
		for x := 0; x < f.Width; x++ {
			vec := f.Data[y*f.Width+x]

			// Convert to int16 scaled values
			// int16 handles -32768 to 32767, covering our -100.00 to 100.00 range easily
			// Convert to int16 scaled values
			// int16 handles -32768 to 32767, covering our -100.00 to 100.00 range easily
			xInt := int16(math.Round(vec.Vx * ScaleFactor))
			yInt := int16(math.Round(vec.Vy * ScaleFactor))

			// Cast to uint16 to get the raw bit pattern (Two's Complement for negatives)
			xUint := uint16(xInt)
			yUint := uint16(yInt)

			// Direct slice access for performance
			// 4 bytes per pixel: R, G, B, A
			img.Pix[i+0] = uint8(xUint >> 8)   // Red: X High
			img.Pix[i+1] = uint8(xUint & 0xFF) // Green: X Low
			img.Pix[i+2] = uint8(yUint >> 8)   // Blue: Y High
			img.Pix[i+3] = uint8(yUint & 0xFF) // Alpha: Y Low

			i += 4
		}
	}

	var buf bytes.Buffer
	encoder := png.Encoder{CompressionLevel: png.DefaultCompression}
	if err := encoder.Encode(&buf, img); err != nil {
		return nil, fmt.Errorf("failed to encode png: %w", err)
	}

	return buf.Bytes(), nil
}

// UnmarshalPNG reads PNG data and reconstructs the Frame.
func UnmarshalPNG(data []byte) (*Frame, error) {
	reader := bytes.NewReader(data)
	return DecodePNG(reader)
}

// DecodePNG decodes a PNG from an io.Reader into a Frame.
func DecodePNG(r io.Reader) (*Frame, error) {
	img, err := png.Decode(r)
	if err != nil {
		return nil, fmt.Errorf("failed to decode png image: %w", err)
	}

	bounds := img.Bounds()
	width := bounds.Dx()
	height := bounds.Dy()
	frame := NewFrame(width, height)

	// We need to handle different image types returned by decode
	// Ideally, it's NRGBA, but we should support generic fallback just in case
	switch src := img.(type) {
	case *image.NRGBA:
		// Fast path for NRGBA (expected)
		i := 0
		for y := 0; y < height; y++ {
			for x := 0; x < width; x++ {
				xHigh := uint16(src.Pix[i+0])
				xLow := uint16(src.Pix[i+1])
				yHigh := uint16(src.Pix[i+2])
				yLow := uint16(src.Pix[i+3])

				// Reconstruct uint16
				xUint := (xHigh << 8) | xLow
				yUint := (yHigh << 8) | yLow

				// Cast back to int16 to restore sign, then float
				frame.Data[y*width+x] = Vector{
					Vx: float64(int16(xUint)) / ScaleFactor,
					Vy: float64(int16(yUint)) / ScaleFactor,
				}
				i += 4
			}
		}
	default:
		// Slower fallback for other image types (e.g. RGBA, NRGBA64)
		// Note: If the PNG was saved as standard RGBA (premultiplied),
		// data stored in Alpha channel might be corrupted/modulated.
		// We assume the input was generated by our MarshalPNG (NRGBA).
		for y := 0; y < height; y++ {
			for x := 0; x < width; x++ {
				c := img.At(x+bounds.Min.X, y+bounds.Min.Y)
				r, g, b, a := c.RGBA() // Returns values in [0, 0xFFFF]

				// c.RGBA() is premultiplied. This is risky for data storage if not NRGBA.
				// However, if we are recovering standard 8-bit data:
				// The Go image library scales 8-bit up to 16-bit by duplicating bytes (e.g. 0xFF -> 0xFFFF).
				// We take the top 8 bits to get back to raw bytes.

				r8 := uint8(r >> 8)
				g8 := uint8(g >> 8)
				b8 := uint8(b >> 8)
				a8 := uint8(a >> 8)

				xUint := (uint16(r8) << 8) | uint16(g8)
				yUint := (uint16(b8) << 8) | uint16(a8)

				frame.Data[y*width+x] = Vector{
					Vx: float64(int16(xUint)) / ScaleFactor,
					Vy: float64(int16(yUint)) / ScaleFactor,
				}
			}
		}
	}

	return frame, nil
}

type Sequence struct {
	Frames []*Frame
}

func (s *Sequence) MarshalSequence() ([][]byte, error) {
	out := make([][]byte, len(s.Frames))
	for i, frame := range s.Frames {
		b, err := frame.MarshalPNG()
		if err != nil {
			return nil, fmt.Errorf("failed to marshal frame %d: %w", i, err)
		}
		out[i] = b
	}
	return out, nil
}

// ValidateValue checks if a value fits within the int16 range
func ValidateValue(v float64) error {
	scaled := v * ScaleFactor
	if scaled < -32768 || scaled > 32767 {
		return errors.New("value out of range for int16 packing")
	}
	return nil
}
